facebook/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
=begin
     resources :users, only: [:index, :new, :create] do
	resources :addresses, only: [:show, :new, :create, :update]
end
=end

resources :users do
  	  resources :addresses	
	  resources :posts
	end
  # get 'users/index'
root 'users#index'
end

facebook/app/models/address.rb
# == Schema Information
#
# Table name: addresses
#
#  id         :integer          not null, primary key
#  country    :string
#  state      :string
#  city       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  userid     :string
#

class Address < ApplicationRecord
	belongs_to :user
	validates :state, :city, :country, presence: true
end

facebook/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

facebook/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id          :integer          not null, primary key
#  title       :string
#  text        :string
#  no_of_likes :integer
#  user_id_id  :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Post < ApplicationRecord
  belongs_to :user
  validates :title, :text, :no_of_likes, presence: true

end

facebook/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id            :integer          not null, primary key
#  name          :string
#  gender        :string
#  date_of_birth :datetime
#  email         :string
#  password      :string
#

class User < ApplicationRecord

	validates :name, presence: true, format: { with: /\A[a-zA-Z ]+\z/, message: 'Invalid' }
	validates :gender, presence: true, inclusion: {in: ['male','female']}
	validates :email, presence: true,  format: { with: /\A[a-zA-Z]+\w*@\w+[.][a-z]{3}\z/, message: 'Invalid email'} 
	validates :password, presence: true, confirmation: true, length: { minimum: 6}
	validates :date_of_birth, presence: true
	has_one :address
	has_many :posts

	def is_female?
	  gender == 'female'
	end

	def is_valid_date?
	   date_of_birth < Time.now.strftime("%d-%m-%Y")
	end
end

facebook/app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
	def index
		@users = User.all
		@u = @users.find_by(id: params[:user_id])
		@address = Address.find_by(user_id: params[:user_id])
	end

	def show
		@address = Address.find_by(user_id: params[:user_id])
	end

	def new
		@address =Address.new
		@user = User.find(params[:user_id])
	end

	def create
      @address =Address.new(address_params)
      @user = User.find_by(id: params[:user_id])
	  @user.address = @address
	  redirect_to user_addresses_path(@user)
		#render 'index'
	end

	def update
  	  @address = Address.find(params[:user_id])
      if @address.update(address_params)
      	redirect_to users_path
      else
        render 'edit'
      end
    end

  	def edit
  	  @address = Address.find_by(user_id: params[:user_id])
  	end

  	def destroy
  	  Address.find_by(user_id: params[:user_id]).destroy
  	  redirect_to users_path
  	end

  	private
  	def address_params
  	  params.require(:address).permit(:city, :state, :country, :user_id)
  	end
  end

facebook/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery with: :exception
end

facebook/app/controllers/users_controller.rb
class UsersController < ApplicationController
	# include UsersHelper
  
  def index
  	@users =User.all
      #	@mydate = format_time(Time.now) #helper methods can be accessed in views not in controller
    
    respond_to do |format|
      format.html
      format.xml { render :xml => @users.to_xml }
      format.json { render json: @users }
    end

  end
  
  def new
  	@user =User.new
  end
  
  def show
  	@user =User.find_by(params[:id])
  end

  def create
  	@user = User.new(user_params)
    if @user.save
  		redirect_to users_path
  	else
  		render :new
  	end
  end

  def update
  	 @user = User.find(params[:id])
 
    if @user.update(user_params)
      redirect_to users_path
    else
      render 'edit'
    end
  end

  def edit
  	@user = User.find(params[:id])
  end

  def destroy
  	User.find(params[:id]).destroy
  	redirect_to users_path
  end

  private
  def user_params
  	params.require(:user).permit(:name, :gender, :email, :password, :password_confirmation, :date_of_birth )
  end
end

facebook/app/helpers/addresses_helper.rb
module AddressesHelper
end

facebook/app/helpers/application_helper.rb
module ApplicationHelper
end

facebook/app/helpers/users_helper.rb
module UsersHelper
	def format_time date
		date.strftime("%d-%m-%Y")
	end
end

facebook/app/views/addresses/edit.html.haml
Edit address

facebook/app/views/addresses/index.html.haml
!!!
%html
  %body
    %center
      %h3
        Address of the user
        %br/
        = format_time(Time.now)
    %br/
    %h2
      %center
        - unless @address.nil?
          Id : #{@address.user_id}
          %br/
          Name : #{@u.name}
          %br/
          City : #{@address.city}
          %br/
          State : #{@address.state}
          %br/
          Country : #{@address.country}
          %br/
          %br/
          = link_to 'Edit Address', edit_user_address_path
        - else
          = 'Address does not exist for '
          = @users.find_by(id: params[:user_id]).name
          %br/
          %br/
          = link_to 'Add address', new_user_address_path(params[:user_id])
        %br/
        = link_to 'SHOW ALL USERS', users_path
      %h2

facebook/app/views/addresses/new.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Add address
  %body
    = form_for(@address, url: user_addresses_path(@user.id), method: :POST ) do |f|
      = f.label :city
      %br/
      = f.text_field :city
      = @user.errors.full_messages_for(:city) if @user.errors.messages[:city]
      %br/
      = f.label :state
      %br/
      = f.text_field :state
      = @user.errors.full_messages_for(:state) if @user.errors.messages[:state]
      %br/
      = f.label :'country'
      %br/
      = f.text_field :country
      = @user.errors.full_messages_for(:country) if @user.errors.messages[:country]
      %br/
      %br/
      = f.submit

facebook/app/views/addresses/show.html.haml
show.html.erb

facebook/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Facebook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

facebook/app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Facebook
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

facebook/app/views/users/edit.html.haml
%h1 Edit User
= form_with(model: @user) do |f|
  = f.label :name
  %br/
  = f.text_field :name
  = @user.errors.full_messages_for(:name) if @user.errors.messages[:name]
  %br/
  = f.label :gender
  %br/
  = f.text_field :gender
  = @user.errors.full_messages_for(:gender) if @user.errors.messages[:gender]
  %br/
  = f.label :date_of_birth
  %br/
  = f.date_field :date_of_birth
  = @user.errors.full_messages_for(:date_of_birth) if @user.errors.messages[:date_of_birth]
  %br/
  = f.label :email
  %br/
  = f.text_field :email
  = @user.errors.full_messages_for(:email) if @user.errors.messages[:email]
  %br/
  = f.label :password
  %br/
  = f.password_field :password
  = @user.errors.full_messages_for(:password) if @user.errors.messages[:password]
  %br/
  = f.label :password_confirmed, "Confirmation"
  %br/
  = f.password_field :password_confirmation
  = @user.errors.full_messages_for(:password) if @user.errors.messages[:password]
  %br/
  = f.submit
= link_to 'Back', users_path

facebook/app/views/users/index.erb
<html>
<body>
<center>
<h3>All user details</h3></center>
<br>
<table align="center" border=1>
<th>Name</th><th>Gender</th><th>Email</th><th>Date of birth</th>
<% @users.each do |user| %>
<tr>
<td>
	<%= user.name %>
</td>
<td>
	<%= user.gender %>
</td>
<td>
	<%= user.email %>
</td>
<td>
	<%= user.date_of_birth %>
</td>

<tr>
<% end %>

</table>
</body>
</html>

facebook/app/views/users/index.html.erb
<html>
<body>
<center>
<h3>List of all users<br>
<%= format_time(Time.now) %>
</h3></center>
<br>
<table align="center" border=1>
<th>Name</th><th>Gender</th><th>Email</th><th>Date of birth</th>
<% @users.each do |user| %>
<tr>
<td>
	<%= user.name %>
</td>
<td>
	<%= user.gender %>
</td>
<td>
	<%= user.email %>
</td>
<td>
	<%= format_time(user.date_of_birth) %>
</td>
<td>
<%= link_to 'Delete', user, method: :delete %>
</td>
<td>
<%= link_to 'Update', user, method: :edit %>
</td>

<tr>
<% end %>

</table>
<center><h3><%= link_to 'Create New User', new_user_path %></h3></center>
</body>
</html>

facebook/app/views/users/index.html.haml
!!!
%html
  %body
    %center
      %h3
        List of all users
        %br/
        = format_time(Time.now)
    %br/
    %table{:align => "center", :border => "1", :cellpadding => "10"}
      %th Name
      %th Gender
      %th Email
      %th Date of birth
      %th Delete
      %th Edit
      %th Address
      %th View Posts
      - @users.each do |user|
        %tr
          %td
            = user.name
          %td
            = user.gender
          %td
            = user.email
          %td
            = format_time(user.date_of_birth)
          %td
            = link_to 'Delete User', user, method: :delete, data: { confirm: 'Are you sure?' }
          %td
            = link_to 'Update', edit_user_path(user)
          %td
            = link_to 'View Address', user_addresses_path(user)
          %td
            = link_to 'View all post'
    %center
      %h3
        = link_to 'Create New User', new_user_path

facebook/app/views/users/new.html.erb
<center>
<h1>Sign Up</h1>

<%= form_for(@user) do |f| %>
	<%= f.label :name %>
	<br>
	<%= f.text_field :name %>
	<br>
	<%= f.label :gender %>
	<br>
	<%= f.text_field :gender %>
	<br>
	<%= f.label :'Date of Birth' %>
	<br>
	<%= f.date_field :date_of_birth %>
	<br>
	<%= f.label :email %>
	<br>
	<%= f.text_field :email %>
	<br>
	<%= f.label :password %>
	<br>
	<%= f.password_field :password %>
	<br>
	<%= f.label :password_confirmed, "Confirmation" %>


<br>


	<%= f.password_field :password_confirmation %>
	<br> <%= f.submit %>
	 <% end %>
 <h3>
<%= link_to 'Back', users_path %>
</h3>
</center>

facebook/app/views/users/new.html.haml
%center
  %h1 Sign Up
  = form_for(@user) do |f|
    = f.label :name
    %br/
    = f.text_field :name
    = @user.errors.full_messages_for(:name) if @user.errors.messages[:name]
    %br/
    = f.label :gender
    %br/
    = f.text_field :gender
    = @user.errors.full_messages_for(:gender) if @user.errors.messages[:gender]
    %br/
    = f.label :'Date of Birth'
    %br/
    = f.date_field :date_of_birth
    = @user.errors.full_messages_for(:date_of_birth) if @user.errors.messages[:date_of_birth]
    %br/
    = f.label :email
    %br/
    = f.text_field :email
    = @user.errors.full_messages_for(:email) if @user.errors.messages[:email]
    %br/
    = f.label :password
    %br/
    = f.password_field :password
    = @user.errors.full_messages_for(:password) if @user.errors.messages[:password]
    %br/
    = f.label :password_confirmed, "Confirmation"
    %br/
    = f.password_field :password_confirmation
    = @user.errors.full_messages_for(:password) if @user.errors.messages[:password]
    %br/
    = f.submit
  %h3
    = link_to 'Back', users_path